### ISSUE TITLE
The extension is no longer working for me in Chrome as of Sept 6th.

### ISSUE THREAD

**Issue by DeluxeIncorporated** [fanfare/googleimagesrestored#16]

**Comment by thinkpad4** [comment]
Working for me

**Comment by fanfare** [comment]
it's working for me also -- can you specify which Chrome build you're using, the OS, and whether or not you've installed any extensions after you installed this one? Also -- there's been intermittent issues with people having the extension not working depending on whether or not they're logged into google - which I don't know why that is, but it would be helpful to debug it on someone's browser where it isn't working, maybe if it's throwing any console errors or anything else.

**Comment by thinkpad4** [comment]
It works on Chrome 57 and Chrome 70 on Windows 7 64bit

**Comment by DeluxeIncorporated** [comment]
Chrome Version 76.0.3809.132 (Official Build) (64-bit), Windows 7 64 bit, I haven't been logged out of google. I don't remember installing any extensions after this one.

**Comment by fanfare** [comment]
I downloaded that exact Chrome version and did find an issue with Google Images showing image results which were actually Ads -- which i haven't noticed any of those in the version I was using, which is interesting. When I clicked on an ad, the extension kind of went haywire because of some errors, and that should be fixed in the version I just uploaded (0.1.4) .. although I don't know if that's the same issue you were having, e.g. it not working at all.

You mentioned that it is 'no longer' working, so I can only assume it had been working previously, and then stopped working? I'm unable to replicate the extension not working at all unfortunately, but let me know if the bugfix in 0.1.4 possibly resolves it for you. Thanks

**Comment by DeluxeIncorporated** [comment]
Thanks for the help. Unfortunately 0.1.4 isn't working for me in Chrome either. (But works fine in Firefox). 

Yes, the extension was working perfectly for me  in Chrome originally, I don't know what I did that might have changed something. Thinking back, I may have installed & quickly uninstalled "Bandcamp MP3-128 saver" or "Flash Video Downloader" in the time between when googleimagesrestored was working & stopped working, but I can't remember 100%. 

I tried disabling my other extensions that I've had in Chrome for years (ublock, great suspender, stylus, autohide downloads bar, fireshot, image background color) & I also tried logging out of google as well trying a different google account, but the issue persists.

**Comment by fanfare** [comment]
Just to verify, does the extension not even seem to be loaded whatsoever? Like, if you click on an image, does a preview of the image load up in the side panel on the right as if the extension isn't even enabled? That could be indicative of something else maybe.

**Comment by DeluxeIncorporated** [comment]
Yes, exactly. It's as if the extension isn't working at all. I've tried uninstalling & reinstalling it a couple times as well & it hasn't made a difference.

**Comment by fanfare** [comment]
That is very good to know, I wonder if it has something to do with the manifest. If you wouldn't mind, I would really appreciate it if you could verify something --
could you open google images, search for 'test' and then hit f12 to open the console and see if Google Images Restored is even visible in the frame dropdown, like this: https://i.imgur.com/utWuywa.png

**Comment by DeluxeIncorporated** [comment]
Yes, I see it in the list when I check there.

**Comment by fanfare** [comment]
thanks for checking. I'm kind of stumped really :( Particularly since the extension seems to be loaded on that page, but not getting initialized. I've been looking around to see what's up with extensions randomly not working, and have found some things talking about corrupt chrome profiles, and other cases where extensions suddenly stop working. The only thing I can think of are following the instructions here https://support.google.com/chrome/answer/3296214?hl=en . Sorry I can't be more of assistance.

**Comment by DeluxeIncorporated** [comment]
Resetting Chrome actually seems to have worked. The extension is working again.

Thanks for the help!

**Comment by fanfare** [comment]
awesome. glad that worked out :)
