### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by derrapf** [fanfare/googleimagesrestored#17]
Hi
I just installed it on chrome and firefox
But nothing changes.
There is still the new layout when searching for pics
Did I miss something?
Ralf

**Comment by fanfare** [comment]
still works for me; are you installing it from https://chrome.google.com/webstore/detail/google-images-restored/ncndcebmkibkhopclfdjfacgfholcghi?hl=en and https://addons.mozilla.org/en-US/firefox/addon/google-images-restored/ ? what version and OS?

**Comment by Sxderp** [comment]
Actually, I think this may be some A/B rollout with image search. I noticed the add-on wasn't working as well. I took a look at the page source and noticed, much to my chagrine, CSS classnames were hashed. Looks like Google (like Reddit) is moving to using something like 'css-modules' which will compile CSS classes into some 'scoped' nonsense. The end result, hashed class names and fucktons of annoyance for userscripts.

**Comment by fanfare** [comment]
I definitely don't think the extension is indefinitely sustainable unfortunately, but it seems like they've been using the same consistent hashed classes for years, even after some layout changes, on key elements (e.g. Q7Rsec, etc), so I'm hoping the main core of the script will stay in tact. I guess if the extension does break globally at some point it will be worth trying a new strategy, because I really refuse to ever 'deal' with that new side bar image preview nonsense
