### ISSUE TITLE
thing I found out while messing with the extension 

### ISSUE THREAD

**Issue by ultracoolboy** [fanfare/googleimagesrestored#32]
so when I'm logged into my google account the extension dose not work but when I clear my cookies and fully loggged out of my google account the extension then works up untill I log back into my google account, kinda inconvient since I have to keep logging back in if I want to enjoy the old layout

also another thing is that I have to keep removing the extension because while im logged into my google account not only dose it not work but scolling down the image just don't show up anymore on preview and instead some color blocks, like like how if you disconnect from the internet and half the page stops loading, something like that. 

so yea clearing cookies and logging back in dose not work but staying logged out of my google account works, apparently.

**Comment by fanfare** [comment]
the main reason I haven't tried to get this extension working universally is because when I clear the NID cookie (even when logged in) it has consistently gotten it to work again.. even if it takes like 10 tries to get it to work. getting this thing to work across the board is going to be such a pain, because they keep changing the structure of their HTML and its like cat and mouse trying to fix it. so I figure that would really only be necessary if it breaks *for everyone* unless someone else wants to attempt to fix it... but something to try maybe is to log out and get it to work and then copy the value of the NID cookie then log back in and see if the NID cookie changes (breaking the extension) and then pasting back in the value of the NID cookie that worked.
i cant even imagine what is going on behind the scenes for real because the structure of the HTML and javascript is getting more and more insane with every update

**Comment by LunaAshai** [comment]
Tried to overwrite the NID cookie with a working value but it just overwrote itself.
Then tried to set it to readonly, but that broke being signed in, so that isn't an option either.

On another note: One of my google accounts can still use the extension while logged in, and I have no idea why.

**Comment by pj-camp** [comment]
> 
> 
> so I figure that would really only be necessary if it breaks _for everyone_ 

It looks like it pretty much breaks for everyone.

I used EditThisCookie to block the NID cookie entirely. And it does. And that has no effect.

**Comment by fanfare** [comment]
updated to 0.2.0 to support v2 of google images' newer front/backend scheme
