### ISSUE TITLE
Last 2-3 images in a row are not clickable sometimes

### ISSUE THREAD

**Issue by ArthurPoghosyan** [fanfare/googleimagesrestored#43]
Installed it on 4 different computers using Firefox and sometimes the last 2 or 3 pictures in a row become unclickable. I have no idea what causes this and can't perfectly replicate it every time. Once I restart Firefox the issue usually goes away. This never happened before I installed this add-on, which by the way is a blessing.

I've got these add-ons installed in addition to GIR:
uBlock
Honey
DuckDuckGo Privacy Essentials
Terms of Service; Didn’t Read
No YouTube Comments (Abdullah Diaa)
YouTube Container (Abdullah Diaa)
No Coin - Block miners on the web! (Keraf)

**Comment by fanfare** [comment]
i cant reproduce this issue locally. when you hover over a thumbnail (that you cant click on) does it show the size of the image at the bottom like its supposed to, or does nothing show up

**Comment by Sxderp** [comment]
Nothing shows up when hovering, because you're not actually hovering over them. I think I got this to reproduce with direct links but if I clicked on the "image search" button it wouldn't reproduce.

Looking at the DOM (inspect element) there's an "empty" (opaque: 0? unsure) object. I think it's used for the right hand scrolly thing normally. I just set the z-index to some negative number and that solved my problem.

**Comment by Sxderp** [comment]
I forgot to mention. I did this about a week ago (lol similar time to the issue), so I'm fuzzy on the details.

**Comment by ArthurPoghosyan** [comment]
Sorry for the late response guys. A bit busy here job-wise. I just tried it again and couldn't reproduce the problem. But I swear this was happening before my post on a daily basis.

Yes, when this issue occurred and I hovered over the pictures located in the last 2-3 columns it would not show the size of the image at the bottom like it's supposed to.
