### ISSUE TITLE
Bug /conflict with others extensions

### ISSUE THREAD

**Issue by mikhoul** [fanfare/googleimagesrestored#49]
Hi @fanfare ,

First thanks for this marvelous extension. :+1: 

I use a 2 others userscripts  that no longer works with "Google Image Restored" sadly.

They are [Mouseover Popup Image Viewer](https://github.com/tophf/mpiv) and [Google DWIMages](https://greasyfork.org/fr/scripts/29420-google-dwimages)  .

What happen is that when I use MPIV over the image MPIV is not able to retrieve the image to show the full size image.  And with DWImages when I click on the image nothing happen I can't access the direct link..

I use latest Chromium/Brave so if you need more information just ask me.

**_Small Request:_** I use mainly your extension  to  see the size of the images before using them so I'd really like to have the **option of always showing the size of the image without the need to hover** on the image to see the size.

Regards :octocat:

**Comment by fanfare** [comment]
hey mikhoul. im afraid i can't provide support for third party extensions, just because there's too many to try and make exceptions for, it would be an endless struggle. the thing with the option of always showing sizes,  the only thing i want to focus on with this extension is recapturing the old functionality without adding anything else extra. if you want to modify the source code and load it in manually, take a look at line `367` of `js/main.js` in this repository and change it to:
      sheet.insertRule(`div[jscontroller="${jscontroller}"] .gishoverinfo {pointer-events:none!important;display:inline-block!important}`,0)
that will force the size info to be on permanently

**Comment by mikhoul** [comment]
By commenting line ~384 to 516 and make the modification to line 367 I've succeeded to have only the size info and I removed the listener too.

The problem was that you replace/add many elements in the CSS/html so other extensions don't find them so they don't work.

So it's a quick dirty hack but now it work fine with my setup. 

Maybe later I will fork it or make a userscript to have it more clean/tidy.


Thanks :octocat:
