### ISSUE TITLE
Why is there a difference between the two pictures?

### ISSUE THREAD

**Issue by RadicalNoise** [fanfare/googleimagesrestored#60]
This is the image that opens with the extension's "View Image" button.

https://cdn.lavinya.net/cache/72d3d7ca/av3c8a421dafc90bbe683.jpeg

<details>
 <summary>IMG</summary>

 
![newtab](https://user-images.githubusercontent.com/74098460/102004132-090c1780-3d1f-11eb-8cd8-347498574efa.png)

</details>

---

This is an image where the site is visited and the image is opened in a new tab.

https://cdn.lavinya.net/cache/72d3d7ca/ava1d4bab75683cd74683.jpeg

<details>
 <summary>IMG</summary>

 
![lavinya net](https://user-images.githubusercontent.com/74098460/102004108-d06c3e00-3d1e-11eb-97aa-26d16ea16caf.png)

</details>

---

The difference between the two is that the extension shows the image in a larger size.
The image opened in the new tab is smaller.

I've experienced this case on another sites as well.
I don't know if it's a bug or normal behavior.

<details>
 <summary>IMG</summary>

 
![imgonline-com-ua-twotoone-45yij4jQ0DGTj6](https://user-images.githubusercontent.com/74098460/102004353-fdb9eb80-3d20-11eb-93b7-41b95f002f80.png)

</details>

**Comment by fanfare** [comment]
this isn't because of this extension. look at the source code for the page in question - https://lavinya.net/resim/417/agac-yesil you can find the larger image url in the source code, but it isnt displayed visually anywhere on the page. google just scraped the larger version found in the source code when it crawled the site.
