### ISSUE TITLE
[BUG] Holding down CTRL while clicking the View Image button no longer opens the image in a new tab.

### ISSUE THREAD

**Issue by idgas01** [fanfare/googleimagesrestored#72]
So if you right-click the View Image button, it will open the image in a new tab.  But I have always preferred the "hold down CTRL" while left-clicking to open the image in a new tab.  And that has always worked for me, using your Firefox extension, until around a week ago.  I was wondering if you could do anything to fix and restore this behavior.  Thanks.

**Comment by fanfare** [comment]
I just tried holding down CTRL and left-clicking on the 'View Image' button and the image pops up in a new tab. Did you install any other extension that might be interfering with this one? It could be a case of A/B testing since I can't reproduce it on my end. Are there any errors in the DevTools console? Does anything happen at all when you click?

**Comment by idgas01** [comment]
Oh, sorry about that.  I have an extension called Popup Blocker Ultimate and I must have accidentally removed the Google domain from my whitelist.  It's fixed now.  Closing the thread.
