### ISSUE TITLE
[Bug Report] It does not work on a lot of images (sometimes over half of them).

### ISSUE THREAD

**Issue by gaveitatry2** [fanfare/googleimagesrestored#90]
I have had this problem for a long time now. Maybe even a year. I have just procrastinated and been reluctant to provide proof. But I decided to record it just now. I did a search for a TV actress on how she looked 20 years ago. Half the images did not show a preview. But this happens on just about everything. It doesn't have to be from 20 years ago. There will always be some images that don't have a preview. Sometimes it is just a few images that don't have previews. Sometimes like in this case, it is a lot. Here is a video to demonstrate what I mean.

https://user-images.githubusercontent.com/75463665/226936942-85876b1d-29b3-4d93-b808-f1e5afc0678f.mp4

**Comment by fanfare** [comment]
do you know what version of google images restored you are using? is the browser you are using firefox? if so, i think the version of the extension you are using is an older one, because in a newer one, it would have removed the favicons next to the titles and removed the rounded edges of the thumbnails and some other things as well; try uninstalling google images restored completely, then installing the latest version which is here https://addons.mozilla.org/en-US/firefox/addon/google-images-restored-backup/

**Comment by gaveitatry2** [comment]
Thank you. That worked.
