### ISSUE TITLE
Remove the "Related searches" in Google Images

### ISSUE THREAD

**Issue by MossyMosMos** [fanfare/googleimagesrestored#93]
now. i've been recently seen the "Related searches" boxes in google images now, i'm not sure if it a recent feature in google images, or maybe  a new google image's layout make these boxes return, but could you remove that out? @fanfare 
<img width="948" alt="googleimgrelatedsearches" src="https://github.com/fanfare/googleimagesrestored/assets/126743138/f398d990-39a4-46bc-a1ba-7bdbebe467a2">

**Comment by fanfare** [comment]
thanks, i identified the issue and published a new release [`0.5.1`](https://github.com/fanfare/googleimagesrestored/releases/tag/0.5.1) which removes the related searches. ill publish the release to the chrome web store to firefox addons shortly.

**Comment by MossyMosMos** [comment]
thanks for a new version release, but how could i install the update of this extension?

**Comment by fanfare** [comment]
which browser are you using? if firefox, uninstall the old version first, then install the new version from here: https://addons.mozilla.org/en-US/firefox/addon/google-images-restored-backup/
if chrome, ideally wait a few days for it to automatically update (they have to manually 'approve' it first unfortunately)

**Comment by MossyMosMos** [comment]
i used both chrome and edge, but i don't know how could i early-install from zip files. @fanfare

**Comment by MossyMosMos** [comment]
i just want to know how to load the extension from the zip files

**Comment by MossyMosMos** [comment]
this fix also remove the "popular searches" and popular topics" boxes too?

**Comment by fanfare** [comment]
it should remove those boxes that are scattered throughout the results, i dont remember what they are called i thought it was like 'related searches' or something, but anything of that nature should be removed. if it isnt ill try and get rid of it, but i havent seen any since i added the latest version. if you get the latest zip (v3 for chrome) unzip it somewhere to a folder on your computer then follow these instructions https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/

**Comment by fanfare** [comment]
latest version now in both the chrome store and firefox
