### ISSUE TITLE
related images not showing up (resolved)

### ISSUE THREAD

**Issue by fanfare** [fanfare/googleimagesrestored#94]
just making this issue to say im aware google images changed today causing the extension to break and am currently working on fixing it

**Comment by fanfare** [comment]
the issue (related images not showing up) should be resolve in version `0.5.2` -- keeping this open for now because an old version was submitted to the chrome web store and will not be publicly available on there probably for a few days unfortunately.

**Comment by BloodRaynare** [comment]
Sorry if I seem to hijack this open issue.
But I just want to report that while it was fixed with guest account, it still doesn't show with logged-in accounts.

Guest, non-logged account.

![image](https://github.com/fanfare/googleimagesrestored/assets/46045141/ff118514-9965-4ede-ba22-a3503842589f)

Logged-in account.

![image](https://github.com/fanfare/googleimagesrestored/assets/46045141/06c3de3f-d354-41e6-8f14-f5491634f360)

Tested on Firefox 114.0.1

**Comment by MossyMosMos** [comment]
> Guest, non-logged account.
> 
> ![image](https://user-images.githubusercontent.com/46045141/246586149-ff118514-9965-4ede-ba22-a3503842589f.png)
> 
me too, now it's also don't show the related images with both google account sign-out and sign-in too.

**Comment by fanfare** [comment]
i was able to reproduce the issue locally, i just uploaded a new version [`0.5.3`](https://github.com/fanfare/googleimagesrestored/releases/tag/0.5.3) which have it working when both logged out and logged in for both chrome and firefox. hopefully this patches things up. ill upload to the chrome web store once they let me submit a new version.

**Comment by MossyMosMos** [comment]
thanks so much for fixes, but i'm not sure if related images are become much more randomly generated now, is that normal?

**Comment by fanfare** [comment]
if depends on the search query, but everything on my end seems normal at the moment, i havent noticed it being more random

**Comment by fanfare** [comment]
latest version now in both the chrome store and firefox
